name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (or Python, etc.)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm test

    - name: Run Integration Tests
      run: npm run test:integration

    - name: Scan dependencies (Snyk)
      uses: snyk/actions/node@master
      continue-on-error: true
      with:
        command: test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Notify Slack on failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: "❌ PR Checks failed for ${{ github.event.pull_request.html_url }}"
